# Generated by Django 5.0.4 on 2024-04-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('trainName', models.CharField(max_length=40)),
                ('berth', models.CharField(max_length=20)),
                ('classs', models.CharField(max_length=20)),
                ('fromm', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
            ],
        ),
    ]
